using Sunfish.Foundation.Recovery;

namespace Sunfish.Foundation.Recovery.Tests;

/// <summary>
/// Phase 1 G6 sub-pattern #48c (paper-key fallback) — coverage for
/// <see cref="PaperKeyDerivation"/>. Verifies the BIP-39 24-word codec
/// is byte-deterministic (same root seed → same phrase), round-trips
/// cleanly (entropy → phrase → entropy), and rejects invalid inputs
/// (wrong word count, unknown word, bad checksum) before returning
/// any bytes the caller might mistakenly use as a root seed.
/// </summary>
/// <remarks>
/// Includes the official BIP-39 English test vectors from the spec
/// (<see href="https://github.com/trezor/python-mnemonic/blob/master/vectors.json"/>)
/// for the 256-bit-entropy cases; if these regress, the codec is
/// non-conformant and any paper key the user prints today won't be
/// recoverable by a third-party BIP-39 tool tomorrow.
/// </remarks>
public sealed class PaperKeyDerivationTests
{
    [Fact]
    public void ToMnemonic_is_deterministic_for_the_same_seed()
    {
        var seed = new byte[PaperKeyDerivation.EntropyByteLength];
        for (var i = 0; i < seed.Length; i++) seed[i] = (byte)i; // 00 01 02 ... 1F

        var phraseA = PaperKeyDerivation.ToMnemonic(seed);
        var phraseB = PaperKeyDerivation.ToMnemonic(seed);

        Assert.Equal(phraseA, phraseB);
        Assert.Equal(PaperKeyDerivation.MnemonicWordCount, phraseA.Split(' ').Length);
    }

    [Fact]
    public void ToMnemonic_then_FromMnemonic_round_trips_a_random_seed()
    {
        // Sunfish's KeystoreRootSeedProvider produces 32-byte cryptographically random
        // seeds. Verify the codec preserves arbitrary entropy losslessly.
        var seed = new byte[PaperKeyDerivation.EntropyByteLength];
        new Random(42).NextBytes(seed);

        var phrase = PaperKeyDerivation.ToMnemonic(seed);
        var recovered = PaperKeyDerivation.FromMnemonic(phrase);

        Assert.Equal(seed, recovered);
    }

    [Fact]
    public void Round_trip_preserves_entropy_for_all_zero_seed()
    {
        var seed = new byte[PaperKeyDerivation.EntropyByteLength];
        var phrase = PaperKeyDerivation.ToMnemonic(seed);
        var recovered = PaperKeyDerivation.FromMnemonic(phrase);
        Assert.Equal(seed, recovered);
    }

    [Fact]
    public void Round_trip_preserves_entropy_for_all_ones_seed()
    {
        var seed = Enumerable.Repeat((byte)0xFF, PaperKeyDerivation.EntropyByteLength).ToArray();
        var phrase = PaperKeyDerivation.ToMnemonic(seed);
        var recovered = PaperKeyDerivation.FromMnemonic(phrase);
        Assert.Equal(seed, recovered);
    }

    [Theory]
    // Official BIP-39 test vectors from the Trezor python-mnemonic library
    // (https://github.com/trezor/python-mnemonic/blob/master/vectors.json) — 256-bit
    // entropy entries. If these regress, the codec is non-conformant and a paper
    // key generated by Sunfish today would not round-trip via a third-party BIP-39
    // tool. Format: hex-entropy → expected 24-word phrase.
    [InlineData(
        "0000000000000000000000000000000000000000000000000000000000000000",
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art")]
    [InlineData(
        "7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f",
        "legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth title")]
    [InlineData(
        "8080808080808080808080808080808080808080808080808080808080808080",
        "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic bless")]
    [InlineData(
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo vote")]
    public void ToMnemonic_matches_official_BIP39_vectors(string entropyHex, string expectedPhrase)
    {
        var entropy = Convert.FromHexString(entropyHex);
        var phrase = PaperKeyDerivation.ToMnemonic(entropy);
        Assert.Equal(expectedPhrase, phrase);
    }

    [Theory]
    [InlineData(
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
        "0000000000000000000000000000000000000000000000000000000000000000")]
    [InlineData(
        "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo vote",
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")]
    public void FromMnemonic_matches_official_BIP39_vectors(string phrase, string expectedEntropyHex)
    {
        var recovered = PaperKeyDerivation.FromMnemonic(phrase);
        Assert.Equal(expectedEntropyHex, Convert.ToHexString(recovered).ToLowerInvariant());
    }

    [Fact]
    public void ToMnemonic_throws_on_seed_of_wrong_length()
    {
        var ex = Assert.Throws<ArgumentException>(() => PaperKeyDerivation.ToMnemonic(new byte[16]));
        Assert.Contains("32", ex.Message);
    }

    [Fact]
    public void FromMnemonic_throws_on_wrong_word_count()
    {
        var ex = Assert.Throws<FormatException>(() =>
            PaperKeyDerivation.FromMnemonic("abandon abandon abandon"));
        Assert.Contains("24", ex.Message);
    }

    [Fact]
    public void FromMnemonic_throws_on_unknown_word()
    {
        // 24 words but one of them is invalid.
        var phrase = string.Join(' ', Enumerable.Repeat("abandon", 23).Append("notaword"));
        var ex = Assert.Throws<FormatException>(() => PaperKeyDerivation.FromMnemonic(phrase));
        Assert.Contains("notaword", ex.Message);
    }

    [Fact]
    public void FromMnemonic_throws_when_checksum_byte_does_not_match()
    {
        // Take a valid phrase but flip its last word to a different valid word so the
        // checksum byte no longer matches SHA-256(entropy).
        var seed = Enumerable.Repeat((byte)0x42, PaperKeyDerivation.EntropyByteLength).ToArray();
        var validPhrase = PaperKeyDerivation.ToMnemonic(seed).Split(' ');
        validPhrase[^1] = validPhrase[^1] == "zone" ? "zoo" : "zone";
        var corrupted = string.Join(' ', validPhrase);

        var ex = Assert.Throws<FormatException>(() => PaperKeyDerivation.FromMnemonic(corrupted));
        Assert.Contains("checksum", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void FromMnemonic_normalizes_whitespace_and_case()
    {
        var seed = new byte[PaperKeyDerivation.EntropyByteLength];
        new Random(7).NextBytes(seed);
        var phrase = PaperKeyDerivation.ToMnemonic(seed);

        // User retypes with mixed case + extra spacing.
        var mangled = phrase.ToUpperInvariant().Replace(" ", "   ");
        var recovered = PaperKeyDerivation.FromMnemonic(mangled);
        Assert.Equal(seed, recovered);
    }
}
