using Sunfish.UIAdapters.Blazor.Internal.Interop;
using Sunfish.Foundation.Enums;
using Sunfish.UICore.Contracts;

namespace Sunfish.UIAdapters.Blazor.Tests;

internal sealed class StubCssProvider : ISunfishCssProvider
{
    public string ContainerClass(string? size = null) => string.Empty;
    public string GridClass() => string.Empty;
    public string RowClass() => string.Empty;
    public string ColumnClass(int? span = null, int? offset = null) => string.Empty;
    public string StackClass(StackDirection orientation) => string.Empty;
    public string DividerClass(bool vertical) => string.Empty;
    public string PanelClass() => string.Empty;
    public string DrawerClass(DrawerPosition position, bool isOpen) => string.Empty;
    public string AppBarClass(AppBarPosition position) => string.Empty;
    public string AccordionClass() => string.Empty;
    public string AccordionItemClass(bool isExpanded) => string.Empty;
    public string TabsClass(TabPosition position, TabAlignment alignment, TabSize size) => string.Empty;
    public string TabClass(bool isActive, bool isDisabled) => string.Empty;
    public string TabPanelClass(bool isActive, bool persistContent) => string.Empty;
    public string StepperClass() => string.Empty;
    public string StepClass(StepStatus status) => string.Empty;
    public string SplitterClass(SplitterOrientation orientation) => string.Empty;
    public string DrawerOverlayClass() => string.Empty;
    public string ContextMenuClass() => string.Empty;
    public string NavBarClass() => string.Empty;
    public string NavMenuClass() => string.Empty;
    public string NavItemClass(bool isActive) => string.Empty;
    public string BreadcrumbClass() => string.Empty;
    public string BreadcrumbItemClass() => string.Empty;
    public string MenuClass() => string.Empty;
    public string MenuItemClass(bool isDisabled) => string.Empty;
    public string MenuDividerClass() => string.Empty;
    public string PaginationClass() => string.Empty;
    public string PaginationItemClass(bool isActive) => string.Empty;
    public string TreeViewClass() => string.Empty;
    public string TreeItemClass(bool isExpanded, bool isSelected) => string.Empty;
    public string ToolbarClass() => string.Empty;
    public string EnvironmentBadgeClass(string env) => string.Empty;
    public string TimeRangeSelectorClass() => string.Empty;
    public string ToolbarButtonClass(bool isDisabled = false) => string.Empty;
    public string ToolbarToggleButtonClass(bool isActive, bool isDisabled = false) => string.Empty;
    public string ToolbarSeparatorClass() => string.Empty;
    public string ToolbarGroupClass() => string.Empty;
    public string LinkClass() => string.Empty;
    public string ButtonClass(ButtonVariant variant, ButtonSize size, bool isOutline, bool isDisabled) => string.Empty;
    public string ButtonClass(ButtonVariant variant, ButtonSize size, FillMode fillMode, RoundedMode rounded, bool isDisabled) => string.Empty;
    public string IconButtonClass(ButtonSize size) => string.Empty;
    public string ButtonGroupClass() => string.Empty;
    public string ToggleButtonClass(bool selected) => string.Empty;
    public string SplitButtonClass() => string.Empty;
    public string ChipClass(ChipVariant variant, bool isSelected) => string.Empty;
    public string ChipSetClass() => string.Empty;
    public string FabClass(FabSize size) => string.Empty;
    public string TextBoxClass(bool isInvalid, bool isDisabled) => string.Empty;
    public string TextAreaClass(bool isInvalid) => string.Empty;
    public string NumericInputClass() => string.Empty;
    public string SearchBoxClass() => string.Empty;
    public string AutocompleteClass() => string.Empty;
    public string AutocompleteClass(bool isOpen, bool isDisabled, bool isInvalid) => string.Empty;
    public string AutocompleteItemClass(bool isHighlighted, bool isSelected) => string.Empty;
    public string SelectClass(bool isInvalid) => string.Empty;
    public string CheckboxClass(bool isChecked) => string.Empty;
    public string RadioClass(bool isSelected) => string.Empty;
    public string RadioGroupClass() => string.Empty;
    public string SwitchClass(bool isOn) => string.Empty;
    public string SliderClass() => string.Empty;
    public string SliderClass(SliderOrientation orientation) => string.Empty;
    public string RatingClass() => string.Empty;
    public string ColorPickerClass() => string.Empty;
    public string ColorPickerPopupClass() => string.Empty;
    public string ColorGradientClass() => string.Empty;
    public string ColorPaletteClass() => string.Empty;
    public string FlatColorPickerClass() => string.Empty;
    public string DatePickerClass() => string.Empty;
    public string TimePickerClass() => string.Empty;
    public string TimePickerPopupClass() => string.Empty;
    public string DateRangePickerClass() => string.Empty;
    public string DateRangePickerPopupClass() => string.Empty;
    public string DateTimePickerClass() => string.Empty;
    public string DateTimePickerPopupClass() => string.Empty;
    public string FileUploadClass() => string.Empty;
    public string FileUploadFileListClass() => string.Empty;
    public string FileUploadDropZoneClass(bool isDragOver, bool isDisabled) => string.Empty;
    public string DropDownListClass(bool isOpen, bool isDisabled, bool isInvalid) => string.Empty;
    public string DropDownListPopupClass() => string.Empty;
    public string DropDownListItemClass(bool isHighlighted, bool isSelected) => string.Empty;
    public string ComboBoxClass(bool isOpen, bool isDisabled, bool isInvalid) => string.Empty;
    public string ComboBoxPopupClass() => string.Empty;
    public string ComboBoxItemClass(bool isHighlighted, bool isSelected) => string.Empty;
    public string MultiSelectClass(bool isOpen, bool isDisabled, bool isInvalid) => string.Empty;
    public string MultiSelectPopupClass() => string.Empty;
    public string MultiSelectItemClass(bool isHighlighted, bool isSelected) => string.Empty;
    public string MultiSelectTagClass() => string.Empty;
    public string DropdownPopupClass() => string.Empty;
    public string FormClass() => string.Empty;
    public string FieldClass() => string.Empty;
    public string LabelClass() => string.Empty;
    public string InputGroupClass() => string.Empty;
    public string ValidationMessageClass(ValidationSeverity severity) => string.Empty;
    public string CardClass() => string.Empty;
    public string CardHeaderClass() => string.Empty;
    public string CardBodyClass() => string.Empty;
    public string CardActionsClass() => string.Empty;
    public string CardFooterClass() => string.Empty;
    public string CardImageClass() => string.Empty;
    public string ListClass() => string.Empty;
    public string ListItemClass() => string.Empty;
    public string TableClass() => string.Empty;
    public string AvatarClass(AvatarSize size) => string.Empty;
    public string BadgeClass(BadgeVariant variant) => string.Empty;
    public string TooltipClass(TooltipPosition position) => string.Empty;
    public string TooltipClass(TooltipPosition position, TooltipShowOn showOn) => string.Empty;
    public string PopoverClass() => string.Empty;
    public string TimelineClass() => string.Empty;
    public string TimelineItemClass() => string.Empty;
    public string CarouselClass() => string.Empty;
    public string TypographyClass(TypographyVariant variant) => string.Empty;
    public string AlertClass(AlertSeverity severity) => string.Empty;
    public string AlertStripClass() => string.Empty;
    public string ToastClass(ToastSeverity severity) => string.Empty;
    public string SnackbarClass() => string.Empty;
    public string SnackbarClass(NotificationVerticalPosition vertical, NotificationHorizontalPosition horizontal) => string.Empty;
    public string SnackbarHostClass() => string.Empty;
    public string DialogClass() => string.Empty;
    // ADR 0023 — per-slot dialog classes. Stubs return non-empty tokens so
    // the `Dialog_SlotMethods_AllReturn_NonEmpty` parity contract is mirrored
    // by any test-local provider as well.
    public string DialogDialogClass() => "stub-dialog";
    public string DialogContentClass() => "stub-dialog__content";
    public string DialogHeaderClass() => "stub-dialog__header";
    public string DialogTitleClass() => "stub-dialog__title";
    public string DialogBodyClass() => "stub-dialog__body";
    public string DialogFooterClass() => "stub-dialog__footer";
    public string DialogOverlayClass() => string.Empty;
    public string DialogCloseMarkup() => string.Empty;
    public string DialogCloseButtonClass() => string.Empty;
    public string ProgressBarClass() => string.Empty;
    public string ProgressCircleClass() => string.Empty;
    public string SpinnerClass(SpinnerSize size) => string.Empty;
    public string SkeletonClass(SkeletonVariant variant) => string.Empty;
    public string CalloutClass(CalloutType type) => string.Empty;
    public string DataGridClass() => string.Empty;
    public string DataGridTableClass() => string.Empty;
    public string DataGridHeaderClass() => string.Empty;
    public string DataGridHeaderCellClass(bool isSortable, bool isSorted) => string.Empty;
    public string DataGridRowClass(bool isSelected, bool isStriped) => string.Empty;
    public string DataGridCellClass() => string.Empty;
    public string DataGridCommandButtonClass() => string.Empty;
    public string DataGridPagerClass() => string.Empty;
    public string DataGridToolbarClass() => string.Empty;
    public string DataGridFilterRowClass() => string.Empty;
    public string DataGridFilterCellClass() => string.Empty;
    public string DataGridGroupHeaderClass() => string.Empty;
    public string DataSheetClass(bool isLoading) => string.Empty;
    public string DataSheetCellClass(CellState state, bool isActive, bool isEditable) => string.Empty;
    public string DataSheetHeaderCellClass(bool isSortable) => string.Empty;
    public string DataSheetRowClass(bool isDirty, bool isSelected, bool isDeleted) => string.Empty;
    public string DataSheetToolbarClass() => string.Empty;
    public string DataSheetBulkBarClass(bool isVisible) => string.Empty;
    public string DataSheetSaveFooterClass(int dirtyCount) => string.Empty;
    public string DataSheetAddButtonClass() => string.Empty;
    public string DataSheetSaveButtonClass() => string.Empty;
    public string DataSheetResetButtonClass() => string.Empty;
    public string DataSheetSpinnerClass() => string.Empty;
    public string DataSheetDirtyBadgeClass() => string.Empty;
    public string DataSheetSkeletonClass() => string.Empty;
    public string DataSheetSkeletonRowClass() => string.Empty;
    public string DataSheetSkeletonCellClass() => string.Empty;
    public string DataSheetLoadingTextClass() => string.Empty;
    public string DataSheetEmptyClass() => string.Empty;
    public string DataSheetSelectHeaderClass() => string.Empty;
    public string DataSheetActionsHeaderClass() => string.Empty;
    public string DataSheetAriaLiveClass() => string.Empty;
    public string DataSheetSelectCellClass() => string.Empty;
    public string DataSheetActionsCellClass() => string.Empty;
    public string DataSheetDeleteButtonClass() => string.Empty;
    public string DataSheetCellTextClass() => string.Empty;
    public string DataSheetEditorInputClass() => string.Empty;
    public string DataSheetEditorSelectClass() => string.Empty;
    public string DataSheetContentClass() => string.Empty;
    public string DataSheetScreenReaderOnlyClass() => string.Empty;
    public string ListViewClass() => string.Empty;
    public string ListViewItemClass(bool isSelected) => string.Empty;
    public string WindowClass(bool isModal) => string.Empty;
    public string WindowTitleBarClass() => string.Empty;
    public string WindowContentClass() => string.Empty;
    public string WindowActionsClass() => string.Empty;
    public string WindowOverlayClass() => string.Empty;
    public string WindowFooterClass() => string.Empty;
    public string EditorClass() => string.Empty;
    public string EditorToolbarClass() => string.Empty;
    public string EditorContentClass() => string.Empty;
    public string UploadClass() => string.Empty;
    public string UploadFileListClass() => string.Empty;
    public string UploadFileItemClass() => string.Empty;
    public string UploadDropZoneClass(bool isActive) => string.Empty;
    public string ChartContainerClass() => string.Empty;
    public string GaugeClass() => string.Empty;
    public string CalendarClass() => string.Empty;
    public string SchedulerClass() => string.Empty;
    public string AllocationSchedulerClass() => string.Empty;
    public string AllocationSchedulerToolbarClass() => string.Empty;
    public string AllocationSchedulerResourceColumnClass(bool isPinned) => string.Empty;
    public string AllocationSchedulerTimeHeaderClass(TimeGranularity grain) => string.Empty;
    public string AllocationSchedulerRowClass(bool isSelected, bool isOverAllocated, bool isStriped = false) => string.Empty;
    public string AllocationSchedulerCellClass(bool isEditable, bool isSelected, bool isConflict, bool isDisabled, bool isDragTarget) => string.Empty;
    public string AllocationSchedulerCellValueClass(AllocationValueMode mode) => string.Empty;
    public string AllocationSchedulerDeltaClass(DeltaDisplayMode mode, bool isOver, bool isUnder) => string.Empty;
    public string AllocationSchedulerScenarioStripClass() => string.Empty;
    public string AllocationSchedulerScenarioChipClass(bool isActive, bool isLocked) => string.Empty;
    public string AllocationSchedulerGhostBarClass() => string.Empty;
    public string AllocationSchedulerContextMenuClass() => string.Empty;
    public string AllocationSchedulerEmptyClass() => string.Empty;
    public string AllocationSchedulerLoaderClass() => string.Empty;
    public string AllocationSchedulerSplitterClass(bool isDragging, bool isFocused) => string.Empty;
    public string AllocationSchedulerSplitterRestoreClass(SplitterSide collapsedSide) => string.Empty;
    public string ModalClass(ModalSize size) => string.Empty;
    public string ModalOverlayClass() => string.Empty;
    public string SignalRStatusClass(AggregateConnectionState state, bool isCompact) => string.Empty;
    public string SignalRPopupClass() => string.Empty;
    public string SignalRRowClass(ConnectionHealthState health) => string.Empty;
    public string SignalRBadgeClass(ConnectionHealthState health) => string.Empty;
    public string ResizableContainerClass(bool isResizing, bool isDisabled) => string.Empty;
    public string ResizableContainerContentClass() => string.Empty;
    public string ResizableContainerHandleClass(ResizeEdges edge, bool isActive, bool isFocused) => string.Empty;
    public string IconClass(string iconName, IconSize size, IconFlip flip = IconFlip.None, IconThemeColor themeColor = IconThemeColor.Base) => string.Empty;
    public string DragDropClass() => string.Empty;
    public string DropZoneClass(bool isActive) => string.Empty;
    public string ScrollViewClass() => string.Empty;
}

internal sealed class StubIconProvider : ISunfishIconProvider
{
    public string GetIcon(string name, IconSize size = IconSize.Medium) => string.Empty;
    public string GetIconSpriteUrl() => string.Empty;
}

/// <summary>No-op download service stub for tests that render SunfishDataGrid but do not exercise export.</summary>
internal sealed class StubDownloadService : IDownloadService
{
    public ValueTask DownloadAsync(DownloadRequest request, CancellationToken cancellationToken = default)
        => ValueTask.CompletedTask;
}
