// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sunfish.Foundation.Assets.Postgres;

#nullable disable

namespace Sunfish.Foundation.Assets.Postgres.Migrations
{
    [DbContext(typeof(AssetStoreDbContext))]
    [Migration("20260418144952_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sunfish.Foundation.Assets.Postgres.Audit.AuditRow", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamptz")
                        .HasColumnName("at");

                    b.Property<string>("EntityAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_authority");

                    b.Property<string>("EntityLocalPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_local_part");

                    b.Property<string>("EntityScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_scheme");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<int>("Op")
                        .HasColumnType("integer")
                        .HasColumnName("op");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<long?>("PrevAuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("prev_audit_id");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("VersionHash")
                        .HasColumnType("text")
                        .HasColumnName("version_hash");

                    b.Property<int?>("VersionSequence")
                        .HasColumnType("integer")
                        .HasColumnName("version_sequence");

                    b.HasKey("AuditId");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_at");

                    b.HasIndex("EntityScheme", "EntityAuthority", "EntityLocalPart", "At")
                        .HasDatabaseName("ix_audit_entity_at");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Sunfish.Foundation.Assets.Postgres.Entities.EntityRow", b =>
                {
                    b.Property<string>("EntityScheme")
                        .HasColumnType("text")
                        .HasColumnName("entity_scheme");

                    b.Property<string>("EntityAuthority")
                        .HasColumnType("text")
                        .HasColumnName("entity_authority");

                    b.Property<string>("EntityLocalPart")
                        .HasColumnType("text")
                        .HasColumnName("entity_local_part");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreationIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creation_issuer");

                    b.Property<string>("CreationNonce")
                        .HasColumnType("text")
                        .HasColumnName("creation_nonce");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_hash");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer")
                        .HasColumnName("current_sequence");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityScheme", "EntityAuthority", "EntityLocalPart");

                    b.HasIndex("Schema")
                        .HasDatabaseName("ix_entities_schema");

                    b.HasIndex("Tenant")
                        .HasDatabaseName("ix_entities_tenant");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Sunfish.Foundation.Assets.Postgres.Hierarchy.ClosureRow", b =>
                {
                    b.Property<long>("ClosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("closure_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClosureId"));

                    b.Property<string>("AncestorAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ancestor_authority");

                    b.Property<string>("AncestorLocalPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ancestor_local_part");

                    b.Property<string>("AncestorScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ancestor_scheme");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("DescendantAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descendant_authority");

                    b.Property<string>("DescendantLocalPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descendant_local_part");

                    b.Property<string>("DescendantScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descendant_scheme");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("ClosureId");

                    b.HasIndex("DescendantScheme", "DescendantAuthority", "DescendantLocalPart")
                        .HasDatabaseName("ix_closure_descendant");

                    b.HasIndex("AncestorScheme", "AncestorAuthority", "AncestorLocalPart", "DescendantScheme", "DescendantAuthority", "DescendantLocalPart", "Depth", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("ux_closure_edge_from");

                    b.ToTable("hierarchy_closure", (string)null);
                });

            modelBuilder.Entity("Sunfish.Foundation.Assets.Postgres.Hierarchy.EdgeRow", b =>
                {
                    b.Property<long>("EdgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("edge_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EdgeId"));

                    b.Property<string>("FromAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_authority");

                    b.Property<string>("FromLocalPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_local_part");

                    b.Property<string>("FromScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_scheme");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("ToAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_authority");

                    b.Property<string>("ToLocalPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_local_part");

                    b.Property<string>("ToScheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_scheme");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("EdgeId");

                    b.HasIndex("Kind", "FromScheme", "FromAuthority", "FromLocalPart")
                        .HasDatabaseName("ix_hierarchy_edges_from");

                    b.HasIndex("Kind", "ToScheme", "ToAuthority", "ToLocalPart")
                        .HasDatabaseName("ix_hierarchy_edges_to");

                    b.ToTable("hierarchy_edges", (string)null);
                });

            modelBuilder.Entity("Sunfish.Foundation.Assets.Postgres.Versions.VersionRow", b =>
                {
                    b.Property<string>("EntityScheme")
                        .HasColumnType("text")
                        .HasColumnName("entity_scheme");

                    b.Property<string>("EntityAuthority")
                        .HasColumnType("text")
                        .HasColumnName("entity_authority");

                    b.Property<string>("EntityLocalPart")
                        .HasColumnType("text")
                        .HasColumnName("entity_local_part");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<string>("DiffJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_json");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("ParentHash")
                        .HasColumnType("text")
                        .HasColumnName("parent_hash");

                    b.Property<int?>("ParentSequence")
                        .HasColumnType("integer")
                        .HasColumnName("parent_sequence");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("EntityScheme", "EntityAuthority", "EntityLocalPart", "Sequence");

                    b.HasIndex("EntityScheme", "EntityAuthority", "EntityLocalPart", "ValidFrom")
                        .HasDatabaseName("ix_versions_entity_valid_from");

                    b.ToTable("versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
