using System.Buffers.Text;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Sunfish.Foundation.Crypto;

/// <summary>
/// A principal identifier — a 32-byte Ed25519 public key that uniquely identifies an actor
/// in the Sunfish decentralization model. Two principals are equal iff their public-key bytes
/// are equal.
/// </summary>
/// <remarks>
/// <para>
/// The default record-struct equality generated by the compiler would compare the underlying
/// <c>byte[]</c> by reference, which makes logically-equal principals compare as unequal.
/// This type overrides <see cref="Equals(PrincipalId)"/> / <see cref="GetHashCode"/> to provide
/// value equality by content. Keep them in sync if you add fields.
/// </para>
/// <para>
/// A default-constructed <c>PrincipalId</c> (<c>default(PrincipalId)</c>) has a <c>null</c>
/// backing array and will throw <see cref="NullReferenceException"/> from members that read it.
/// This is intentional — callers should construct principals via <see cref="FromBytes"/>,
/// <see cref="FromBase64Url"/>, or <see cref="KeyPair.Generate"/> rather than default-initialize.
/// </para>
/// </remarks>
[JsonConverter(typeof(PrincipalIdJsonConverter))]
public readonly record struct PrincipalId
{
    /// <summary>Ed25519 public-key length in bytes (32).</summary>
    public const int LengthInBytes = 32;

    private readonly byte[] _bytes;

    private PrincipalId(byte[] bytes)
    {
        _bytes = bytes;
    }

    /// <summary>Constructs a principal from a 32-byte Ed25519 public key (defensively copied).</summary>
    public static PrincipalId FromBytes(ReadOnlySpan<byte> bytes)
    {
        if (bytes.Length != LengthInBytes)
            throw new ArgumentException($"PrincipalId requires exactly {LengthInBytes} bytes.", nameof(bytes));
        return new PrincipalId(bytes.ToArray());
    }

    /// <summary>Returns the raw public-key bytes as a read-only span.</summary>
    public ReadOnlySpan<byte> AsSpan() => _bytes;

    /// <summary>Returns the base64url (unpadded) string form of the principal.</summary>
    public string ToBase64Url()
    {
        Span<byte> encoded = stackalloc byte[Base64Url.GetEncodedLength(LengthInBytes)];
        Base64Url.EncodeToUtf8(_bytes, encoded, out _, out var written);
        return Encoding.UTF8.GetString(encoded[..written]);
    }

    /// <summary>Parses the base64url string form back into a principal.</summary>
    public static PrincipalId FromBase64Url(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        var utf8 = Encoding.UTF8.GetBytes(value);
        Span<byte> decoded = stackalloc byte[LengthInBytes];
        var status = Base64Url.DecodeFromUtf8(utf8, decoded, out _, out var written);
        if (status != System.Buffers.OperationStatus.Done || written != LengthInBytes)
            throw new FormatException("PrincipalId base64url value is not a valid 32-byte key.");
        return new PrincipalId(decoded.ToArray());
    }

    /// <summary>Value equality over the raw bytes (not reference equality).</summary>
    public bool Equals(PrincipalId other)
        => _bytes.AsSpan().SequenceEqual(other._bytes.AsSpan());

    /// <summary>Hash code derived from the raw bytes; stable across instances with equal content.</summary>
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.AddBytes(_bytes);
        return hash.ToHashCode();
    }

    /// <summary>String form for diagnostics — the base64url public key.</summary>
    public override string ToString() => ToBase64Url();
}

internal sealed class PrincipalIdJsonConverter : JsonConverter<PrincipalId>
{
    public override PrincipalId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var str = reader.GetString() ?? throw new JsonException("PrincipalId must be a base64url string.");
        return PrincipalId.FromBase64Url(str);
    }

    public override void Write(Utf8JsonWriter writer, PrincipalId value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToBase64Url());
    }
}
