using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sunfish.Tooling.DesignTokensCodegen;

/// <summary>
/// Generates <c>tokens.css</c> CSS custom properties from a <see cref="TokenCatalog"/>.
///
/// Color tokens emit three variants:
///   <c>--sf-color-*-light</c>   — explicit light value
///   <c>--sf-color-*-dark</c>    — explicit dark value
///   <c>--sf-color-*</c>         — responsive default (follows OS/theme preference)
///
/// Non-color tokens emit a single flat property.
/// Media blocks are appended for: dark mode, forced-colors, prefers-reduced-motion,
/// prefers-reduced-transparency, and prefers-contrast.
/// </summary>
public static class CssGenerator
{
    public static string Generate(TokenCatalog catalog)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by tooling/design-tokens-codegen — DO NOT EDIT.");
        sb.AppendLine(" * Source: packages/foundation-design-tokens/tokens.json");
        sb.AppendLine(" * Per ADR 0077 §5. Re-generated on every build via BeforeBuild MSBuild target.");
        sb.AppendLine(" */");
        sb.AppendLine();

        // :root — light defaults + explicit -light / -dark variants + flat non-color props
        sb.AppendLine(":root {");

        string? lastGroup = null;
        foreach (var c in catalog.Colors)
        {
            string group = GroupOf(c.CssVar);
            if (group != lastGroup)
            {
                sb.AppendLine();
                sb.AppendLine($"  /* {group} */");
                lastGroup = group;
            }
            // text.tertiary meets WCAG SC 1.4.3 at ≥3:1 (large text / non-text).
            // DO NOT use for normal body text (< 18pt / 14pt-bold) — that requires ≥4.5:1.
            if (c.CssVar.EndsWith("text-tertiary"))
                sb.AppendLine(
                    "  /* ⚠ large-text / non-text use only — ≥3:1 WCAG 1.4.3 (see tokens.md) */");
            sb.AppendLine($"  {c.CssVar}-light: {c.Light};");
            sb.AppendLine($"  {c.CssVar}-dark: {c.Dark};");
            sb.AppendLine($"  {c.CssVar}: var({c.CssVar}-light);");
        }

        sb.AppendLine();
        lastGroup = null;
        foreach (var f in catalog.NonColorProps)
        {
            string group = f.Group ?? GroupOf(f.CssVar);
            if (group != lastGroup)
            {
                sb.AppendLine();
                sb.AppendLine($"  /* {group} */");
                lastGroup = group;
            }
            // Quote font-family values that contain spaces.
            string value = f.Group == "typography" && f.CssVar.Contains("family")
                ? QuoteFontFamilies(f.Value)
                : f.Value;
            sb.AppendLine($"  {f.CssVar}: {value};");
        }

        sb.AppendLine("}");

        // OS-preference: dark mode
        var colorTokens = catalog.Colors.Where(c => c.CssVar.Contains("sf-color")).ToList();
        AppendDarkModeBlock(sb, colorTokens, "@media (prefers-color-scheme: dark)",
            ":root:not([data-theme=\"light\"])");
        // Explicit dark-theme override
        AppendDarkModeBlock(sb, colorTokens, null, "[data-theme=\"dark\"]");

        // OS-preference: prefers-reduced-motion
        var motionDurations = catalog.NonColorProps
            .Where(f => f.CssVar.StartsWith("--sf-motion-duration-"))
            .ToList();
        if (motionDurations.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("/* OS-preference: prefers-reduced-motion */");
            sb.AppendLine("@media (prefers-reduced-motion: reduce) {");
            sb.AppendLine("  :root {");
            foreach (var f in motionDurations)
                sb.AppendLine($"    {f.CssVar}: 0ms;");
            sb.AppendLine("  }");
            sb.AppendLine("}");
        }

        // OS-preference: prefers-reduced-transparency (flatten box-shadows)
        AppendReducedTransparencyBlock(sb);

        // OS-preference: prefers-contrast: more
        AppendHighContrastBlock(sb);

        // Windows High Contrast (forced-colors)
        AppendForcedColorsBlock(sb);

        return sb.ToString();
    }

    private static void AppendDarkModeBlock(
        StringBuilder sb,
        IReadOnlyList<ColorEntry> colorTokens,
        string? mediaWrapper,
        string selector)
    {
        sb.AppendLine();
        if (mediaWrapper != null)
        {
            sb.AppendLine($"/* {(mediaWrapper.StartsWith("@media") ? "OS-preference: dark mode" : "Explicit dark-theme override")} */");
            sb.AppendLine($"{mediaWrapper} {{");
            sb.AppendLine($"  {selector} {{");
            foreach (var c in colorTokens)
                sb.AppendLine($"    {c.CssVar}: var({c.CssVar}-dark);");
            sb.AppendLine("  }");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("/* Explicit dark-theme override */");
            sb.AppendLine($"{selector} {{");
            foreach (var c in colorTokens)
                sb.AppendLine($"  {c.CssVar}: var({c.CssVar}-dark);");
            sb.AppendLine("}");
        }
    }

    private static void AppendReducedTransparencyBlock(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("/* OS-preference: prefers-reduced-transparency */");
        sb.AppendLine("@media (prefers-reduced-transparency: reduce) {");
        sb.AppendLine("  :root {");
        sb.AppendLine("    --sf-elevation-1: none;");
        sb.AppendLine("    --sf-elevation-2: 0 0 0 1px var(--sf-color-text-tertiary);");
        sb.AppendLine("    --sf-elevation-3: 0 0 0 1px var(--sf-color-text-tertiary);");
        sb.AppendLine("    --sf-elevation-modal: 0 0 0 2px var(--sf-color-text-primary);");
        sb.AppendLine("    --sf-elevation-drawer: 0 0 0 2px var(--sf-color-text-primary);");
        sb.AppendLine("  }");
        sb.AppendLine("}");
    }

    private static void AppendHighContrastBlock(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("/* OS-preference: prefers-contrast: more (boosts contrast pairs) */");
        sb.AppendLine("@media (prefers-contrast: more) {");
        sb.AppendLine("  :root {");
        sb.AppendLine("    --sf-color-text-primary-light: #000000;");
        sb.AppendLine("    --sf-color-text-primary-dark: #ffffff;");
        sb.AppendLine("    --sf-color-text-secondary-light: #1a1a1a;");
        sb.AppendLine("    --sf-color-text-secondary-dark: #e5e5e5;");
        sb.AppendLine("    --sf-color-state-focus-ring-light: #0000ff;");
        sb.AppendLine("    --sf-color-state-focus-ring-dark: #60c0ff;");
        sb.AppendLine("  }");
        sb.AppendLine("}");
    }

    private static void AppendForcedColorsBlock(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("/* Windows High Contrast (forced-colors) — defer to system colors */");
        sb.AppendLine("@media (forced-colors: active) {");
        sb.AppendLine("  :root {");
        sb.AppendLine("    --sf-color-surface-primary-light: Canvas;");
        sb.AppendLine("    --sf-color-surface-primary-dark: Canvas;");
        sb.AppendLine("    --sf-color-surface-primary: Canvas;");
        sb.AppendLine("    --sf-color-surface-secondary-light: Canvas;");
        sb.AppendLine("    --sf-color-surface-secondary-dark: Canvas;");
        sb.AppendLine("    --sf-color-surface-secondary: Canvas;");
        sb.AppendLine("    --sf-color-surface-tertiary-light: Canvas;");
        sb.AppendLine("    --sf-color-surface-tertiary-dark: Canvas;");
        sb.AppendLine("    --sf-color-surface-tertiary: Canvas;");
        sb.AppendLine("    --sf-color-text-primary-light: CanvasText;");
        sb.AppendLine("    --sf-color-text-primary-dark: CanvasText;");
        sb.AppendLine("    --sf-color-text-primary: CanvasText;");
        sb.AppendLine("    --sf-color-text-secondary-light: CanvasText;");
        sb.AppendLine("    --sf-color-text-secondary-dark: CanvasText;");
        sb.AppendLine("    --sf-color-text-secondary: CanvasText;");
        sb.AppendLine("    --sf-color-text-tertiary-light: GrayText;");
        sb.AppendLine("    --sf-color-text-tertiary-dark: GrayText;");
        sb.AppendLine("    --sf-color-text-tertiary: GrayText;");
        sb.AppendLine("    --sf-color-state-success-light: LinkText;");
        sb.AppendLine("    --sf-color-state-success-dark: LinkText;");
        sb.AppendLine("    --sf-color-state-success: LinkText;");
        sb.AppendLine("    --sf-color-state-warning-light: Mark;");
        sb.AppendLine("    --sf-color-state-warning-dark: Mark;");
        sb.AppendLine("    --sf-color-state-warning: Mark;");
        sb.AppendLine("    --sf-color-state-error-light: LinkText;");
        sb.AppendLine("    --sf-color-state-error-dark: LinkText;");
        sb.AppendLine("    --sf-color-state-error: LinkText;");
        sb.AppendLine("    --sf-color-state-info-light: LinkText;");
        sb.AppendLine("    --sf-color-state-info-dark: LinkText;");
        sb.AppendLine("    --sf-color-state-info: LinkText;");
        sb.AppendLine("    --sf-color-state-focus-ring-light: Highlight;");
        sb.AppendLine("    --sf-color-state-focus-ring-dark: Highlight;");
        sb.AppendLine("    --sf-color-state-focus-ring: Highlight;");
        sb.AppendLine("  }");
        sb.AppendLine("}");
    }

    private static string GroupOf(string cssVar) =>
        cssVar.StartsWith("--sf-color-surface") ? "sf.color.surface" :
        cssVar.StartsWith("--sf-color-text") ? "sf.color.text" :
        cssVar.StartsWith("--sf-color-state") ? "sf.color.state" :
        cssVar.StartsWith("--sf-color-role-band") ? "sf.color.role-band" :
        cssVar.StartsWith("--sf-typography") ? "sf.typography" :
        cssVar.StartsWith("--sf-space") ? "sf.space" :
        cssVar.StartsWith("--sf-radius") ? "sf.radius" :
        cssVar.StartsWith("--sf-elevation") ? "sf.elevation" :
        cssVar.StartsWith("--sf-motion") ? "sf.motion" :
        cssVar.StartsWith("--sf-target-size") ? "sf.target-size" :
        cssVar;

    private static string QuoteFontFamilies(string value)
    {
        // Only quote individual family names that contain spaces and aren't already quoted.
        var parts = value.Split(',');
        var sb = new StringBuilder();
        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i].Trim();
            if (i > 0) sb.Append(", ");
            if (part.Contains(' ') && !part.StartsWith("\"") && !part.StartsWith("'"))
                sb.Append('"').Append(part).Append('"');
            else
                sb.Append(part);
        }
        return sb.ToString();
    }
}
