using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sunfish.Tooling.DesignTokensCodegen;

/// <summary>
/// Generates <c>tokens.md</c> and <c>role-band-cvd.md</c> from a <see cref="TokenCatalog"/>.
/// </summary>
public static class MarkdownGenerator
{
    public static string GenerateTokensReference(TokenCatalog catalog)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by tooling/design-tokens-codegen — DO NOT EDIT. -->");
        sb.AppendLine("<!-- Source: packages/foundation-design-tokens/tokens.json -->");
        sb.AppendLine();
        sb.AppendLine("# Sunfish Design Token Reference");
        sb.AppendLine();
        sb.AppendLine("Per [ADR 0077 §5](../../../docs/adrs/0077-shared-design-system.md). "
                    + "Tokens follow [W3C Design Tokens format](https://design-tokens.github.io/community-group/format/). "
                    + "Custom properties use `--sf-*` prefix.");
        sb.AppendLine();

        // Color tokens
        sb.AppendLine("## Color Tokens");
        sb.AppendLine();
        sb.AppendLine("Each color token has explicit `-light` and `-dark` variants plus a responsive");
        sb.AppendLine("default (`var(--sf-color-*-light)`) that switches to dark under");
        sb.AppendLine("`prefers-color-scheme: dark` or `[data-theme=\"dark\"]`.");
        sb.AppendLine();
        sb.AppendLine("| CSS Variable | Light | Dark |");
        sb.AppendLine("|---|---|---|");
        foreach (var c in catalog.Colors)
        {
            sb.AppendLine($"| `{c.CssVar}` | `{c.Light}` | `{c.Dark}` |");
        }

        // Non-color tokens
        sb.AppendLine();
        sb.AppendLine("## Typography");
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.typography");

        sb.AppendLine();
        sb.AppendLine("## Spacing (4px grid)");
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.space");

        sb.AppendLine();
        sb.AppendLine("## Radius");
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.radius");

        sb.AppendLine();
        sb.AppendLine("## Elevation");
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.elevation");

        sb.AppendLine();
        sb.AppendLine("## Motion");
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.motion");

        sb.AppendLine();
        sb.AppendLine("## Target Size");
        sb.AppendLine();
        sb.AppendLine("Per WCAG SC 2.5.8 (web 24px) + Apple HIG (iOS 44pt) + Material Design (Android 48dp).");
        sb.AppendLine();
        WriteNonColorGroup(sb, catalog.NonColorProps, "sf.target-size");

        return sb.ToString();
    }

    public static string GenerateCvdReport(
        IReadOnlyList<CvdAuditor.AuditRow> rows,
        double threshold)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- Generated by tooling/design-tokens-codegen — DO NOT EDIT. -->");
        sb.AppendLine("<!-- Source: packages/foundation-design-tokens/tokens.json -->");
        sb.AppendLine();
        sb.AppendLine("# Role-Band CVD ΔE2000 Audit Report");
        sb.AppendLine();
        sb.AppendLine("Per [ADR 0036 CVD precedent](../../../docs/adrs/0036-syncstate-palette.md). "
                    + $"Minimum pairwise ΔE2000 ≥ {threshold} under deuteranopia, protanopia, and tritanopia.");
        sb.AppendLine();
        sb.AppendLine("> **NOTE:** Role-band hues are currently PLACEHOLDER values per Phase 2a.");
        sb.AppendLine("> Phase 2b CVD audit gate activates when final hues are committed.");
        sb.AppendLine();

        bool anyFail = rows.Any(r => !r.Pass);
        string gateStatus = anyFail ? "⛔ FAIL" : "✅ PASS";
        sb.AppendLine($"**Gate status: {gateStatus}**");
        sb.AppendLine();

        sb.AppendLine("| Hue A | Hue B | Light A | Light B | Normal | Protanopia | Deuteranopia | Tritanopia | Min ΔE | Status |");
        sb.AppendLine("|---|---|---|---|---:|---:|---:|---:|---:|---|");

        foreach (var r in rows)
        {
            string hueA = r.HueA.Replace("--sf-color-role-band-", "");
            string hueB = r.HueB.Replace("--sf-color-role-band-", "");
            string status = r.Pass ? "✅" : "⛔";
            sb.AppendLine($"| {hueA} | {hueB} | `{r.HexA}` | `{r.HexB}` "
                        + $"| {r.NormalDeltaE:F1} | {r.ProDeltaE:F1} | {r.DeuterDeltaE:F1} | {r.TriDeltaE:F1} "
                        + $"| **{r.MinDeltaE:F1}** | {status} |");
        }

        if (anyFail)
        {
            sb.AppendLine();
            sb.AppendLine("## Failing Pairs");
            sb.AppendLine();
            foreach (var r in rows.Where(r => !r.Pass))
            {
                string hueA = r.HueA.Replace("--sf-color-role-band-", "");
                string hueB = r.HueB.Replace("--sf-color-role-band-", "");
                sb.AppendLine($"- **{hueA}** × **{hueB}**: min ΔE2000 = {r.MinDeltaE:F1} (required ≥ {threshold})");
            }
        }

        return sb.ToString();
    }

    private static void WriteNonColorGroup(StringBuilder sb, IReadOnlyList<FlatEntry> props, string group)
    {
        var items = props.Where(f => f.Group == group || GroupOf(f.CssVar) == group).ToList();
        if (items.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("| CSS Variable | Value |");
        sb.AppendLine("|---|---|");
        foreach (var f in items)
            sb.AppendLine($"| `{f.CssVar}` | `{f.Value}` |");
    }

    private static string GroupOf(string cssVar) =>
        cssVar.StartsWith("--sf-color-surface") ? "sf.color.surface" :
        cssVar.StartsWith("--sf-color-text") ? "sf.color.text" :
        cssVar.StartsWith("--sf-color-state") ? "sf.color.state" :
        cssVar.StartsWith("--sf-color-role-band") ? "sf.color.role-band" :
        cssVar.StartsWith("--sf-typography") ? "sf.typography" :
        cssVar.StartsWith("--sf-space") ? "sf.space" :
        cssVar.StartsWith("--sf-radius") ? "sf.radius" :
        cssVar.StartsWith("--sf-elevation") ? "sf.elevation" :
        cssVar.StartsWith("--sf-motion") ? "sf.motion" :
        cssVar.StartsWith("--sf-target-size") ? "sf.target-size" :
        cssVar;
}
