#!/usr/bin/env python3
"""Render icm/_state/active-workstreams.md from per-workstream files.

Reads:
    icm/_state/workstreams/_preamble.md   (hand-edited intro + status vocab)
    icm/_state/workstreams/W*.md           (per-workstream files; one per row)
    icm/_state/workstreams/_postamble.md  (hand-edited how-to-use + last-updated)

Emits:
    icm/_state/active-workstreams.md       (regenerated, byte-stable)

CLI:
    python3 tools/icm/render-ledger.py             # regenerate
    python3 tools/icm/render-ledger.py --check     # exit non-zero if regen
                                                   # output differs from the
                                                   # committed ledger

Pure Python 3 stdlib (no PyYAML; minimal hand-rolled frontmatter parser
mirroring tools/adr-projections/project.py).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "icm" / "_state" / "active-workstreams.md"
WORKSTREAMS_DIR = ROOT / "icm" / "_state" / "workstreams"

BANNER = (
    "<!--\n"
    "  DO NOT EDIT THIS FILE.\n"
    "  Regenerated by tools/icm/render-ledger.py from "
    "icm/_state/workstreams/W*.md.\n"
    "  To update a row, edit the corresponding per-workstream file and run:\n"
    "    python3 tools/icm/render-ledger.py\n"
    "  CI verifies regen matches the committed file via "
    "tools/icm/render-ledger.py --check.\n"
    "-->\n"
)


def parse_frontmatter(text: str) -> tuple[dict | None, str]:
    """Minimal YAML frontmatter parser supporting the schema written by
    migrate-ledger.py: scalar string/int values, double-quoted strings with
    \\\" + \\\\ escape sequences."""
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return None, text
    block = text[4:end]
    body = text[end + 5:]
    meta: dict[str, object] = {}
    for line in block.split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        meta[key] = _coerce(val)
    return meta, body


def _coerce(s: str):
    s = s.strip()
    if s == "" or s.lower() == "null":
        return None
    if s.lower() == "true":
        return True
    if s.lower() == "false":
        return False
    if re.match(r"^-?\d+$", s):
        return int(s)
    if s.startswith('"') and s.endswith('"'):
        # Unescape \" and \\.
        return s[1:-1].replace("\\\"", "\"").replace("\\\\", "\\")
    if s.startswith("'") and s.endswith("'"):
        return s[1:-1]
    return s


def parse_notes(body: str) -> str:
    """Extract the body content under '## Notes'.  Returns the raw notes text
    with leading + trailing blank lines stripped."""
    m = re.search(r"^## Notes\s*\n(.*?)\Z", body, flags=re.DOTALL | re.MULTILINE)
    if not m:
        return ""
    notes = m.group(1)
    # Strip leading + trailing blank lines but preserve internal newlines.
    return notes.strip("\n").rstrip()


def collect_rows() -> list[dict]:
    rows: list[dict] = []
    for path in sorted(WORKSTREAMS_DIR.glob("W*.md")):
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        if meta is None:
            print(f"warning: {path} has no frontmatter; skipping",
                  file=sys.stderr)
            continue
        notes = parse_notes(body)
        rows.append({
            "path": path,
            "sort_order": meta.get("sort_order", 0),
            "number": meta.get("number"),
            "slug": meta.get("slug"),
            "title_cell": meta.get("title", ""),
            "status_cell": meta.get("status_cell", ""),
            "owner_cell": meta.get("owner_cell", ""),
            "reference_cell": meta.get("reference_cell", ""),
            "notes": notes,
        })
    rows.sort(key=lambda r: (r["sort_order"], r["number"] or 0, r["slug"] or ""))
    return rows


def render_table(rows: list[dict]) -> str:
    out: list[str] = []
    for r in rows:
        cells = [
            f" {r['number']} ",
            f" {r['title_cell']} ",
            f" {r['status_cell']} ",
            f" {r['owner_cell']} ",
            f" {r['reference_cell']} ",
            f" {r['notes']} ",
        ]
        out.append("|" + "|".join(cells) + "|\n")
    return "".join(out)


def render_ledger() -> str:
    preamble_path = WORKSTREAMS_DIR / "_preamble.md"
    postamble_path = WORKSTREAMS_DIR / "_postamble.md"
    if not preamble_path.exists() or not postamble_path.exists():
        raise SystemExit(
            "Missing _preamble.md or _postamble.md under "
            f"{WORKSTREAMS_DIR.relative_to(ROOT)}.  Run "
            "tools/icm/migrate-ledger.py first."
        )
    preamble = preamble_path.read_text(encoding="utf-8")
    postamble = postamble_path.read_text(encoding="utf-8")
    rows = collect_rows()
    table = render_table(rows)
    return BANNER + preamble + table + postamble


def main() -> int:
    p = argparse.ArgumentParser(
        description="Regenerate icm/_state/active-workstreams.md from "
                    "per-workstream files.",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed ledger differs from regen output",
    )
    args = p.parse_args()

    rendered = render_ledger()
    if args.check:
        if not LEDGER.exists():
            print(f"ledger missing: {LEDGER}", file=sys.stderr)
            return 1
        on_disk = LEDGER.read_text(encoding="utf-8")
        if on_disk != rendered:
            print(
                "active-workstreams.md is out of sync with per-workstream "
                "files.\nRun: python3 tools/icm/render-ledger.py",
                file=sys.stderr,
            )
            # Show a small diff hint.
            import difflib
            diff = "".join(difflib.unified_diff(
                on_disk.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile="active-workstreams.md (on disk)",
                tofile="active-workstreams.md (regenerated)",
                n=2,
            ))
            sys.stderr.write(diff[:4000])
            return 1
        print("active-workstreams.md is up-to-date.")
        return 0
    LEDGER.write_text(rendered, encoding="utf-8")
    print(f"regenerated {LEDGER.relative_to(ROOT)} "
          f"({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
