using System.Reflection;
using Sunfish.Foundation.Base;
using Sunfish.Components.Blazor.Base;
using Sunfish.Foundation.Data;
using Sunfish.Foundation.Enums;
using Sunfish.Components.Blazor.Components.DataDisplay;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace Sunfish.Components.Blazor.Components.DataDisplay;

public partial class SunfishDataGrid<TItem> : SunfishComponentBase
{
    // ── Internal state ─────────────────────────────────────────────────
    internal readonly List<SunfishGridColumn<TItem>> _columns = [];
    internal readonly GridState _state = new();
    internal List<TItem> _displayedItems = [];
    internal HashSet<TItem> _selectedItems = [];
    internal HashSet<TItem> _expandedDetailItems = [];
    internal HashSet<(int RowIndex, string Field)> _selectedCellKeys = new();
    private bool _stateInitialized;

    // Grouping state
    internal List<GridGroupRow<TItem>> _groupedRows = [];
    internal HashSet<string> _collapsedGroups = [];

    // Editing state (managed in SunfishDataGrid.Editing.cs)
    internal TItem? _editingItem;
    internal TItem? _originalItem;
    internal bool _isCreating;
    internal string? _inCellEditingField;

    // Centralized sizing state for header/body alignment.
    internal IColumnWidthProvider _widthProvider = new FixedWidthProvider();
    internal GridLayoutContract _layoutContract = GridLayoutContract.Empty;
    private readonly Dictionary<SunfishGridColumn<TItem>, string> _columnSizingIds = [];

    // AutoGenerate state
    internal bool _autoColumnsGenerated;

    /// <summary>Tracks columns that were created by auto-generation so they can be refreshed without
    /// disturbing explicit <see cref="SunfishGridColumn{TItem}"/> children.</summary>
    internal readonly List<SunfishGridColumn<TItem>> _autoGeneratedColumns = [];

    // Search state
    internal string _searchText = "";
    private CancellationTokenSource? _searchCts;

    // FilterMenu state
    internal string? _filterMenuField;
    internal FilterOperator _filterMenuOperator = FilterOperator.Contains;
    internal string _filterMenuValue = "";

    // CheckBoxList filter state
    internal string? _checkBoxFilterField;
    internal HashSet<string> _checkBoxFilterSelected = new();
    internal List<string> _checkBoxFilterDistinct = new();

    // ── Parameters: Data Binding ────────────────────────────────────────

    /// <summary>Client-side data source. Mutually exclusive with <see cref="OnRead"/>.</summary>
    [Parameter] public IEnumerable<TItem>? Data { get; set; }

    /// <summary>Server-side data read callback. When bound, the grid delegates sorting/filtering/paging to the consumer.</summary>
    [Parameter] public EventCallback<GridReadEventArgs<TItem>> OnRead { get; set; }

    // ── Parameters: Paging ──────────────────────────────────────────────

    /// <summary>Whether paging is enabled.</summary>
    [Parameter] public bool Pageable { get; set; }

    /// <summary>Number of items per page. Defaults to 10.</summary>
    [Parameter] public int PageSize { get; set; } = 10;

    /// <summary>The current page number (1-based). Supports two-way binding.</summary>
    [Parameter] public int Page { get; set; }

    /// <summary>Fires when the current page changes.</summary>
    [Parameter] public EventCallback<int> PageChanged { get; set; }

    /// <summary>Available page sizes for the page-size dropdown. Set to null to hide the dropdown.</summary>
    [Parameter] public int[]? PageSizes { get; set; }

    /// <summary>Fires when the page size changes.</summary>
    [Parameter] public EventCallback<int> PageSizeChanged { get; set; }

    /// <summary>The maximum number of page buttons to show in the pager. Defaults to 5.</summary>
    [Parameter] public int PagerButtonCount { get; set; } = 5;

    // ── Parameters: Sorting, Filtering & Grouping ────────────────────────

    /// <summary>Whether sorting is enabled. Defaults to true.</summary>
    [Parameter] public bool Sortable { get; set; } = true;

    /// <summary>Whether sorting allows single or multiple columns. Defaults to Multiple.</summary>
    [Parameter] public GridSortMode SortMode { get; set; } = GridSortMode.Multiple;

    /// <summary>The filter mode for the grid.</summary>
    [Parameter] public GridFilterMode FilterMode { get; set; } = GridFilterMode.None;

    /// <summary>Whether grouping is enabled. When true, columns can be grouped via the API.</summary>
    [Parameter] public bool Groupable { get; set; }

    /// <summary>Template for group header rows. Receives a <see cref="GridGroupHeaderContext{TItem}"/> as context.</summary>
    [Parameter] public RenderFragment<GridGroupHeaderContext<TItem>>? GroupHeaderTemplate { get; set; }

    /// <summary>Template for group footer rows. Receives a <see cref="GridGroupHeaderContext{TItem}"/> as context.</summary>
    [Parameter] public RenderFragment<GridGroupHeaderContext<TItem>>? GroupFooterTemplate { get; set; }

    // ── Parameters: Selection ───────────────────────────────────────────

    /// <summary>The selection mode for the grid.</summary>
    [Parameter] public GridSelectionMode SelectionMode { get; set; } = GridSelectionMode.None;

    /// <summary>Whether selection operates on rows or cells.</summary>
    [Parameter] public GridSelectionUnit SelectionUnit { get; set; } = GridSelectionUnit.Row;

    /// <summary>The currently selected cells (when SelectionUnit is Cell).</summary>
    [Parameter] public IEnumerable<GridCellReference<TItem>>? SelectedCells { get; set; }

    /// <summary>Event fired when the cell selection changes.</summary>
    [Parameter] public EventCallback<IEnumerable<GridCellReference<TItem>>> SelectedCellsChanged { get; set; }

    /// <summary>Whether to show a checkbox column for selection.</summary>
    [Parameter] public bool ShowCheckboxColumn { get; set; }

    /// <summary>The currently selected items. Supports two-way binding.</summary>
    [Parameter] public IEnumerable<TItem>? SelectedItems { get; set; }

    /// <summary>Fires when the selected items change.</summary>
    [Parameter] public EventCallback<IEnumerable<TItem>> SelectedItemsChanged { get; set; }

    // ── Parameters: Layout & Display ────────────────────────────────────

    /// <summary>Whether to apply striped row styling.</summary>
    [Parameter] public bool Striped { get; set; }

    /// <summary>The height of the grid (e.g. "400px", "50vh"). Enables vertical scrolling.</summary>
    [Parameter] public string? Height { get; set; }

    /// <summary>The width of the grid (e.g. "100%", "800px").</summary>
    [Parameter] public string? Width { get; set; }

    /// <summary>Whether keyboard navigation is enabled within the grid.</summary>
    [Parameter] public bool Navigable { get; set; }

    /// <summary>When true, columns are auto-generated from TItem's public properties if no explicit columns are defined.</summary>
    [Parameter] public bool AutoGenerateColumns { get; set; }

    /// <summary>Whether to use Blazor Virtualize for row rendering.</summary>
    [Parameter] public bool EnableVirtualization { get; set; }

    /// <summary>The overscan count for virtualization (rows rendered outside visible area). Defaults to 5.</summary>
    [Parameter] public int VirtualizeOverscanCount { get; set; } = 5;

    /// <summary>Whether data is currently loading. Shows a loading overlay.</summary>
    [Parameter] public bool IsLoading { get; set; }

    /// <summary>Whether to show a built-in search box above the grid. Searches across all visible columns.</summary>
    [Parameter] public bool ShowSearchBox { get; set; }

    /// <summary>Placeholder text for the search box.</summary>
    [Parameter] public string SearchBoxPlaceholder { get; set; } = "Search...";

    /// <summary>
    /// Debounce delay (in milliseconds) for the search box. After the user stops typing, the filter
    /// is applied after this many milliseconds. Defaults to 300ms.
    /// </summary>
    [Parameter] public int SearchDelay { get; set; } = 300;

    /// <summary>Optional custom width provider. Defaults to <see cref="FixedWidthProvider"/>.</summary>
    [Parameter] public IColumnWidthProvider? ColumnWidthProvider { get; set; }

    /// <summary>
    /// Controls the visual density of the grid. Maps to a root-level CSS class:
    /// <list type="bullet">
    ///   <item><description><see cref="DataGridSize.Small"/> → <c>mar-datagrid--size-small</c></description></item>
    ///   <item><description><see cref="DataGridSize.Medium"/> → <c>mar-datagrid--size-medium</c> (default)</description></item>
    ///   <item><description><see cref="DataGridSize.Large"/> → <c>mar-datagrid--size-large</c></description></item>
    /// </list>
    /// Each tier sets CSS custom properties <c>--mar-datagrid-font-size</c>, <c>--mar-datagrid-cell-padding</c>,
    /// and <c>--mar-datagrid-row-height</c> which are consumed by cell and row styling.
    /// </summary>
    [Parameter] public DataGridSize Size { get; set; } = DataGridSize.Medium;

    /// <summary>
    /// Items that should be visually highlighted. When an item in this collection matches a rendered
    /// row, the CSS class <c>mar-datagrid-row--highlighted</c> is applied to that row's <c>&lt;tr&gt;</c> element.
    /// <para><b>Equality model:</b> reference equality is used by default (matching on the exact same
    /// object reference). For <c>record</c> types where value equality is desired, pass instances that
    /// compare equal to the items in <see cref="Data"/> or the server-loaded data. Internally the grid
    /// materialises a <see cref="HashSet{TItem}"/> once per render pass for O(1) per-row lookup.</para>
    /// </summary>
    [Parameter] public IEnumerable<TItem>? HighlightedItems { get; set; }

    // ── Parameters: Templates ───────────────────────────────────────────

    /// <summary>Column definitions (SunfishGridColumn components).</summary>
    [Parameter] public RenderFragment? ChildContent { get; set; }

    /// <summary>Optional toolbar content rendered above the grid.</summary>
    [Parameter] public RenderFragment? ToolbarTemplate { get; set; }

    /// <summary>Detail row template for master-detail expansion. Receives the row item as context.</summary>
    [Parameter] public RenderFragment<TItem>? DetailTemplate { get; set; }

    /// <summary>
    /// Custom template displayed when the grid has no data (i.e., <see cref="_displayedItems"/> is empty
    /// and no groups are present).
    /// Rendered inside a single <c>&lt;tr&gt;&lt;td colspan="N"&gt;</c> that spans all columns, preserving
    /// table structure. Falls back to a plain "No data available." message when not set.
    /// <para><b>Loading interaction:</b> when <see cref="IsLoading"/> is <c>true</c>, the loading overlay
    /// takes priority and this template is suppressed even if items are empty.</para>
    /// </summary>
    [Parameter] public RenderFragment? NoDataTemplate { get; set; }

    /// <summary>
    /// Custom row template for full control over cell rendering. When set, the grid renders the outer
    /// <c>&lt;tr&gt;</c> element (with all row-level event handlers: click, double-click, context-menu,
    /// selection, drag, detail-expand, and checkbox) and the template is responsible for the inner
    /// <c>&lt;td&gt;</c> cells only.
    /// <para><b>Wrapper convention:</b> the grid owns the <c>&lt;tr&gt;</c>; the template fills the cells.
    /// This matches the Radzen / MudBlazor convention.</para>
    /// <para><b>System columns:</b> drag-handle, detail-expand, and checkbox columns (when enabled) are
    /// rendered by the grid before the template content. The command column (edit/delete) is skipped when
    /// <c>RowTemplate</c> is set — include any command UI inside the template if needed.</para>
    /// <para><b>Events preserved:</b> <see cref="OnRowClick"/>, <see cref="OnRowDoubleClick"/>,
    /// <see cref="OnRowContextMenu"/>, and <see cref="OnRowRender"/> all continue to fire.</para>
    /// </summary>
    [Parameter] public RenderFragment<TItem>? RowTemplate { get; set; }

    // ── Parameters: State Events ────────────────────────────────────────

    /// <summary>Fires once when the grid initializes. Set properties on the provided GridState to restore saved state.</summary>
    [Parameter] public EventCallback<GridState> OnStateInit { get; set; }

    /// <summary>Fires after any state change (page, sort, filter, selection). Use this to persist grid state.</summary>
    [Parameter] public EventCallback<GridStateChangedEventArgs> OnStateChanged { get; set; }

    // ── Parameters: Row Events ──────────────────────────────────────────

    /// <summary>Fires when a row is clicked.</summary>
    [Parameter] public EventCallback<GridRowClickEventArgs<TItem>> OnRowClick { get; set; }

    /// <summary>Fires when a row is double-clicked.</summary>
    [Parameter] public EventCallback<GridRowClickEventArgs<TItem>> OnRowDoubleClick { get; set; }

    /// <summary>Fires when a row is right-clicked.</summary>
    [Parameter] public EventCallback<GridRowClickEventArgs<TItem>> OnRowContextMenu { get; set; }

    /// <summary>Callback for per-row render customization (CSS classes, styles).</summary>
    [Parameter] public Action<GridRowRenderEventArgs<TItem>>? OnRowRender { get; set; }

    /// <summary>Fires when a detail row is expanded.</summary>
    [Parameter] public EventCallback<TItem> OnRowExpand { get; set; }

    /// <summary>Fires when a detail row is collapsed.</summary>
    [Parameter] public EventCallback<TItem> OnRowCollapse { get; set; }

    // ── Parameters: Editing ─────────────────────────────────────────────

    /// <summary>The editing mode. Defaults to None (no editing).</summary>
    [Parameter] public GridEditMode EditMode { get; set; } = GridEditMode.None;

    /// <summary>Fires when the user initiates adding a new item.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnAdd { get; set; }

    /// <summary>Fires when a new item is confirmed for creation.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnCreate { get; set; }

    /// <summary>Fires when an existing item's edit is confirmed.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnUpdate { get; set; }

    /// <summary>Fires when an item is deleted.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnDelete { get; set; }

    /// <summary>Fires when a row enters edit mode.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnEdit { get; set; }

    /// <summary>Fires when editing is cancelled.</summary>
    [Parameter] public EventCallback<GridEditEventArgs<TItem>> OnCancel { get; set; }

    /// <summary>Fires when a new model is needed for creation. Set the Item property on the args.</summary>
    [Parameter] public EventCallback<GridModelInitEventArgs<TItem>> OnModelInit { get; set; }

    /// <summary>Fires when a custom command is executed on a row.</summary>
    [Parameter] public EventCallback<GridCommandEventArgs<TItem>> OnCommand { get; set; }

    /// <summary>Whether to show a confirmation dialog before deleting. Defaults to false.</summary>
    [Parameter] public bool ConfirmDelete { get; set; }

    /// <summary>The confirmation message shown when ConfirmDelete is true.</summary>
    [Parameter] public string ConfirmDeleteText { get; set; } = "Are you sure you want to delete this item?";

    /// <summary>Fires before an export operation. Set IsCancelled to true to prevent the export.</summary>
    [Parameter] public EventCallback<GridExportEventArgs> OnBeforeExport { get; set; }

    /// <summary>Fires after an export operation completes.</summary>
    [Parameter] public EventCallback<GridExportEventArgs> OnAfterExport { get; set; }

    /// <summary>Whether to export all pages or only the current page. Defaults to true.</summary>
    [Parameter] public bool ExportAllPages { get; set; } = true;

    /// <summary>When true, rows show a drag handle and can be reordered via drag-and-drop.</summary>
    [Parameter] public bool RowDraggable { get; set; }

    /// <summary>Fires when a row is dropped to a new position.</summary>
    [Parameter] public EventCallback<GridRowDropEventArgs<TItem>> OnRowDrop { get; set; }

    // ── Column Registry ─────────────────────────────────────────────────

    internal void RegisterColumn(SunfishGridColumn<TItem> column)
    {
        if (!_columns.Contains(column))
        {
            column._columnIndex = _columns.Count;
            _columns.Add(column);

            // When AutoGenerateColumns is active, re-run the reflection pass so that any
            // auto-generated column for the same field is dropped (children win — A2.4).
            if (AutoGenerateColumns)
                RefreshAutoGeneratedColumns();

            ResolveLayoutContract();
            StateHasChanged();
        }
    }

    internal void UnregisterColumn(SunfishGridColumn<TItem> column)
    {
        _columnSizingIds.Remove(column);
        _columns.Remove(column);

        // If auto-gen is active, refresh so the unregistered field's column can be regenerated.
        if (AutoGenerateColumns)
            RefreshAutoGeneratedColumns();

        ResolveLayoutContract();
        StateHasChanged();
    }

    // ── Highlight state ─────────────────────────────────────────────────

    /// <summary>
    /// Cached <see cref="HashSet{TItem}"/> built from <see cref="HighlightedItems"/> once per render pass.
    /// Null when <see cref="HighlightedItems"/> is null (no rows highlighted). Reference equality is used
    /// so that the set correctly identifies the same objects passed as <see cref="Data"/>. If the consumer
    /// already passes an <see cref="ISet{T}"/> of the correct type, we wrap it directly to avoid a copy.
    /// </summary>
    private HashSet<TItem>? _highlightedSet;

    // ── Computed Properties ─────────────────────────────────────────────

    internal List<SunfishGridColumn<TItem>> _visibleColumns => _columns.Where(c => c.Visible).ToList();

    internal int TotalColumnCount =>
        _visibleColumns.Count
        + (RowDraggable ? 1 : 0)
        + (ShowCheckboxColumn ? 1 : 0)
        + (DetailTemplate != null ? 1 : 0)
        + (EditMode != GridEditMode.None && EditMode != GridEditMode.InCell ? 1 : 0);

    internal int TotalPages => _state.TotalCount > 0 && _state.PageSize > 0
        ? (int)Math.Ceiling((double)_state.TotalCount / _state.PageSize)
        : 1;

    /// <summary>
    /// Returns the CSS class that encodes the current <see cref="Size"/> tier.
    /// Applied to the grid's root element alongside the CSS-provider base class.
    /// </summary>
    private string SizeClass => Size switch
    {
        DataGridSize.Small  => "mar-datagrid--size-small",
        DataGridSize.Large  => "mar-datagrid--size-large",
        _                   => "mar-datagrid--size-medium",  // DataGridSize.Medium is the default
    };

    private string? RootStyle
    {
        get
        {
            var parts = new List<string>();
            parts.Add($"width:{Width ?? "100%"};");
            return parts.Count > 0 ? string.Join("", parts) : null;
        }
    }

    private string? ContentStyle
    {
        get
        {
            if (Height == null) return null;
            return $"max-height:{Height};overflow:auto;";
        }
    }

    private string ContentContainerStyle
        => $"width:100%;overflow-x:auto;{ContentStyle}";

    // ── Lifecycle ───────────────────────────────────────────────────────

    protected override async Task OnParametersSetAsync()
    {
        _state.PageSize = PageSize;

        if (Page > 0)
            _state.CurrentPage = Page;

        if (SelectedItems != null)
            _selectedItems = new HashSet<TItem>(SelectedItems);

        // Materialise the highlighted-items set once per render pass for O(1) per-row lookup.
        // Use EqualityComparer<TItem>.Default so that:
        //   – reference types: reference equality (same object identity)
        //   – record / value types: value equality via GetHashCode / Equals
        // If the consumer already passes a HashSet<TItem>, use it directly to avoid an
        // unnecessary copy (the comparer is already the consumer's intended semantics).
        if (HighlightedItems is null)
        {
            _highlightedSet = null;
        }
        else if (HighlightedItems is HashSet<TItem> existingSet)
        {
            _highlightedSet = existingSet;
        }
        else
        {
            _highlightedSet = new HashSet<TItem>(HighlightedItems);
        }

        if (!_stateInitialized)
        {
            _stateInitialized = true;
            if (OnStateInit.HasDelegate)
            {
                await OnStateInit.InvokeAsync(_state);
            }
        }

        // Auto-generate columns from TItem's public properties (A2.1–A2.5).
        // Explicit <SunfishGridColumn> children take priority; auto-generated columns fill the gaps.
        // We regenerate on every parameter-set so that a change to AutoGenerateColumns is reflected.
        if (AutoGenerateColumns)
        {
            RefreshAutoGeneratedColumns();
        }
        else if (_autoColumnsGenerated)
        {
            // AutoGenerateColumns was turned off — remove any previously auto-generated columns.
            RemoveAutoGeneratedColumns();
            _autoColumnsGenerated = false;
        }

        ResolveLayoutContract();

        await ProcessDataAsync();
    }

    internal void ResolveLayoutContract()
    {
        _widthProvider = ColumnWidthProvider ?? new FixedWidthProvider();

        var visible = _visibleColumns;
        var entries = new List<ColumnSizingEntry>(visible.Count);

        for (var i = 0; i < visible.Count; i++)
        {
            var column = visible[i];
            if (!_columnSizingIds.TryGetValue(column, out var id))
            {
                id = string.IsNullOrWhiteSpace(column.Field)
                    ? $"col-{i}"
                    : $"{column.Field}-{i}";
                _columnSizingIds[column] = id;
            }

            entries.Add(new ColumnSizingEntry(
                id,
                column.EffectiveWidth,
                50,
                null,
                column.TextAlign,
                column.Locked,
                column.FrozenPosition));
        }

        _layoutContract = _widthProvider.Resolve(entries);
    }

    private string? GetSizingId(SunfishGridColumn<TItem> column)
        => _columnSizingIds.TryGetValue(column, out var id) ? id : null;

    internal string? GetResolvedColumnWidth(SunfishGridColumn<TItem> column)
    {
        var id = GetSizingId(column);
        if (id is null) return null;
        return _layoutContract.WidthById.TryGetValue(id, out var width) ? width : null;
    }

    internal string? GetColumnWidthStyle(SunfishGridColumn<TItem> column)
    {
        var width = GetResolvedColumnWidth(column);
        return width is null ? null : $"width:{width};";
    }

    internal string? GetColumnCellStyle(SunfishGridColumn<TItem> column, string? extraStyle = null)
    {
        var widthStyle = GetColumnWidthStyle(column);
        var textAlignStyle = column.TextAlign != null ? $"text-align:{column.TextAlign};" : null;
        return string.Join("", new[] { widthStyle, textAlignStyle, extraStyle }.Where(s => !string.IsNullOrEmpty(s)));
    }

    internal string? GetFrozenCellStyle(SunfishGridColumn<TItem> column, bool isHeader = false)
    {
        if (!column.Locked) return null;
        if (!_columnSizingIds.TryGetValue(column, out var id)) return null;
        if (!_layoutContract.FrozenOffsets.TryGetValue(id, out var offset)) return null;

        var side = column.FrozenPosition == GridColumnFrozenPosition.Start ? "left" : "right";
        var zIndex = isHeader ? 3 : 2;
        return $"position:sticky;{side}:{offset}px;z-index:{zIndex};background:var(--sf-color-surface);";
    }

    /// <summary>
    /// Refreshes the set of auto-generated columns from <typeparamref name="TItem"/>'s public properties.
    /// Explicit <see cref="SunfishGridColumn{TItem}"/> children (those NOT in <see cref="_autoGeneratedColumns"/>)
    /// take priority: any field already covered by an explicit column is skipped. Auto-generated columns are
    /// appended after explicit columns in <c>DisplayAttribute.Order</c> order, then declaration order.
    /// </summary>
    private void RefreshAutoGeneratedColumns()
    {
        // Remove stale auto-generated columns before regenerating.
        RemoveAutoGeneratedColumns();

        // Collect field names already claimed by explicit (non-auto-generated) columns.
        var explicitFields = _columns
            .Where(c => !string.IsNullOrEmpty(c.Field))
            .Select(c => c.Field)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var props = typeof(TItem).GetProperties(BindingFlags.Public | BindingFlags.Instance);
        var columnDefs = new List<(PropertyInfo Prop, int Order, string Title, bool Editable)>();

        foreach (var prop in props)
        {
            // Skip indexers and write-only properties (A2.5)
            if (prop.GetIndexParameters().Length > 0 || !prop.CanRead) continue;

            // Skip complex types — only primitives, string, Guid, DateTime*, DateOnly/TimeOnly/TimeSpan,
            // decimal, enums, and nullable variants of those are allowed (A2.5).
            var underlying = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;
            if (!IsSimpleType(underlying)) continue;

            // Check [Display] attribute (A2.3): skip if AutoGenerateField == false
            var displayAttr = prop.GetCustomAttribute<System.ComponentModel.DataAnnotations.DisplayAttribute>();
            if (displayAttr?.GetAutoGenerateField() == false) continue;

            // A2.4: children win — skip fields already covered by an explicit column
            if (explicitFields.Contains(prop.Name)) continue;

            var title = displayAttr?.GetName() ?? SplitCamelCase(prop.Name);
            var order = displayAttr?.GetOrder() ?? int.MaxValue;

            // Check [Editable] attribute (A2.3)
            var editableAttr = prop.GetCustomAttribute<System.ComponentModel.DataAnnotations.EditableAttribute>();
            var editable = editableAttr?.AllowEdit ?? true;

            columnDefs.Add((prop, order, title, editable));
        }

        // Append auto-generated columns after explicit columns, ordered by Display.Order then declaration order.
        foreach (var (prop, _, title, editable) in columnDefs.OrderBy(c => c.Order))
        {
            var col = new SunfishGridColumn<TItem>();
            typeof(SunfishGridColumn<TItem>).GetProperty(nameof(SunfishGridColumn<TItem>.Field))!.SetValue(col, prop.Name);
            typeof(SunfishGridColumn<TItem>).GetProperty(nameof(SunfishGridColumn<TItem>.Title))!.SetValue(col, title);
            if (!editable)
                typeof(SunfishGridColumn<TItem>).GetProperty(nameof(SunfishGridColumn<TItem>.Editable))!.SetValue(col, false);

            _columns.Add(col);
            _autoGeneratedColumns.Add(col);
        }

        _autoColumnsGenerated = true;
    }

    /// <summary>Removes all previously auto-generated columns from the column list.</summary>
    private void RemoveAutoGeneratedColumns()
    {
        foreach (var col in _autoGeneratedColumns)
        {
            _columns.Remove(col);
            _columnSizingIds.Remove(col);
        }
        _autoGeneratedColumns.Clear();
    }

    private static bool IsSimpleType(Type type) =>
        type.IsPrimitive || type.IsEnum || type == typeof(string) || type == typeof(decimal)
        || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan)
        || type == typeof(Guid) || type == typeof(DateOnly) || type == typeof(TimeOnly);

    private static string SplitCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return input;
        var result = new System.Text.StringBuilder();
        for (var i = 0; i < input.Length; i++)
        {
            if (i > 0 && char.IsUpper(input[i]) && !char.IsUpper(input[i - 1]))
                result.Append(' ');
            result.Append(input[i]);
        }
        return result.ToString();
    }

    // ── Public API ──────────────────────────────────────────────────────

    /// <summary>Gets a snapshot of the current grid state.</summary>
    public GridState GetState() => new()
    {
        CurrentPage = _state.CurrentPage,
        PageSize = _state.PageSize,
        SortDescriptors = _state.SortDescriptors.Select(s => new SortDescriptor { Field = s.Field, Direction = s.Direction }).ToList(),
        FilterDescriptors = _state.FilterDescriptors.Select(f => new FilterDescriptor { Field = f.Field, Operator = f.Operator, Value = f.Value }).ToList(),
        CompositeFilterDescriptors = _state.CompositeFilterDescriptors.Select(c => new CompositeFilterDescriptor
        {
            LogicalOperator = c.LogicalOperator,
            Filters = c.Filters.Select(f => new FilterDescriptor { Field = f.Field, Operator = f.Operator, Value = f.Value }).ToList()
        }).ToList(),
        GroupDescriptors = _state.GroupDescriptors.Select(g => new GroupDescriptor { Field = g.Field, Direction = g.Direction }).ToList(),
        TotalCount = _state.TotalCount,
        SearchFilter = _searchText,
        EditItem = _editingItem,
        OriginalEditItem = _originalItem,
        InsertedItem = _isCreating ? _editingItem : default,
        CollapsedGroups = new HashSet<string>(_collapsedGroups),
        ExpandedItems = new HashSet<object>(_expandedDetailItems.Cast<object>()),
        ColumnStates = _visibleColumns.Select((c, i) => new GridColumnState
        {
            Field = c.Field,
            Width = c.EffectiveWidth,
            Order = i,
            Visible = c.Visible,
            ShowColumnMenu = c.ShowColumnMenu,
            VisibleInColumnChooser = c.VisibleInColumnChooser
        }).ToList()
    };

    /// <summary>Whether a row is currently being edited.</summary>
    public bool IsEditing => _editingItem != null;

    /// <summary>Whether a new item is being created.</summary>
    public bool IsCreating => _isCreating;

    /// <summary>Checks if the given item is currently being edited.</summary>
    internal bool IsItemEditing(TItem item) => _editingItem != null && EqualityComparer<TItem>.Default.Equals(_editingItem, item);

    /// <summary>Forces the grid to re-read its data source.</summary>
    public async Task Rebind()
    {
        await ProcessDataAsync();
        StateHasChanged();
    }

    /// <summary>Programmatically sets the grid state and reprocesses data.</summary>
    public async Task SetStateAsync(GridState state)
    {
        if (state.CurrentPage > 0)
            _state.CurrentPage = state.CurrentPage;
        _state.PageSize = state.PageSize > 0 ? state.PageSize : _state.PageSize;
        _state.SortDescriptors = state.SortDescriptors ?? [];
        _state.FilterDescriptors = state.FilterDescriptors ?? [];
        _state.CompositeFilterDescriptors = state.CompositeFilterDescriptors ?? [];
        _state.GroupDescriptors = state.GroupDescriptors ?? [];
        _searchText = state.SearchFilter ?? "";

        if (state.CollapsedGroups != null)
            _collapsedGroups = new HashSet<string>(state.CollapsedGroups);

        if (state.ColumnStates != null && state.ColumnStates.Count > 0)
        {
            foreach (var columnState in state.ColumnStates)
            {
                var column = _columns.FirstOrDefault(c => c.Field == columnState.Field);
                if (column is null) continue;

                column.RuntimeWidth = columnState.Width;
            }
        }

        ResolveLayoutContract();

        await ProcessDataAsync();
        StateHasChanged();
    }

    // ── State Notification ──────────────────────────────────────────────

    internal async Task NotifyPageChanged()
    {
        if (PageChanged.HasDelegate)
            await PageChanged.InvokeAsync(_state.CurrentPage);
    }

    internal async Task NotifyStateChanged(string propertyName)
    {
        if (OnStateChanged.HasDelegate)
        {
            await OnStateChanged.InvokeAsync(new GridStateChangedEventArgs
            {
                PropertyName = propertyName,
                State = GetState()
            });
        }
    }

    internal static string? GetAriaSortValue(SortDescriptor? sort)
    {
        if (sort is null) return null;
        return sort.Direction == SortDirection.Ascending ? "ascending" : "descending";
    }
}
