namespace Sunfish.Blocks.WorkOrders.Models;

/// <summary>
/// A single occurrence of a <see cref="MaintenanceSchedule"/> per
/// <c>blocks-work-schema-design.md</c> §2.10. Generated by the
/// scheduler service for each due date the RRULE produces; transitions
/// from Pending to a terminal state as the assignee executes it.
/// </summary>
public sealed class MaintenanceTask
{
    public MaintenanceTaskId Id { get; private set; }
    public MaintenanceScheduleId ScheduleId { get; private set; }
    public DateOnly DueDate { get; private set; }
    public string Title { get; private set; }
    public MaintenanceTaskStatus Status { get; private set; }

    /// <summary>FK to the elevated <see cref="WorkOrder"/> if dispatched; null while Pending.</summary>
    public WorkOrderId? WorkOrderId { get; private set; }

    public DateTimeOffset? CompletedAt { get; private set; }
    public Guid? CompletedBy { get; private set; }
    public string? Notes { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }
    public Guid CreatedBy { get; private set; }
    public Guid UpdatedBy { get; private set; }

    private MaintenanceTask(
        MaintenanceTaskId id,
        MaintenanceScheduleId scheduleId,
        DateOnly dueDate,
        string title,
        DateTimeOffset createdAt,
        Guid createdBy)
    {
        Id         = id;
        ScheduleId = scheduleId;
        DueDate    = dueDate;
        Title      = title;
        Status     = MaintenanceTaskStatus.Pending;
        CreatedAt  = createdAt;
        UpdatedAt  = createdAt;
        CreatedBy  = createdBy;
        UpdatedBy  = createdBy;
    }

    /// <summary>
    /// Build a new <see cref="MaintenanceTask"/> in
    /// <see cref="MaintenanceTaskStatus.Pending"/>.
    /// </summary>
    public static MaintenanceTask Create(
        MaintenanceScheduleId scheduleId,
        DateOnly dueDate,
        string title,
        Guid createdBy,
        DateTimeOffset? createdAt = null)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("Title must be non-empty.", nameof(title));
        return new MaintenanceTask(
            id:         MaintenanceTaskId.NewId(),
            scheduleId: scheduleId,
            dueDate:    dueDate,
            title:      title,
            createdAt:  createdAt ?? DateTimeOffset.UtcNow,
            createdBy:  createdBy);
    }

    /// <summary>Link this task to the dispatched work order.</summary>
    public void DispatchTo(WorkOrderId workOrderId, Guid updatedBy, DateTimeOffset? updatedAt = null)
    {
        if (WorkOrderId is not null)
            throw new InvalidOperationException(
                $"MaintenanceTask {Id.Value} is already dispatched to WorkOrder {WorkOrderId.Value.Value}.");
        WorkOrderId = workOrderId;
        UpdatedBy   = updatedBy;
        UpdatedAt   = updatedAt ?? DateTimeOffset.UtcNow;
    }

    /// <summary>Mark the task complete.</summary>
    public void Complete(Guid completedBy, string? notes = null, DateTimeOffset? completedAt = null)
    {
        Status      = MaintenanceTaskStatus.Completed;
        CompletedAt = completedAt ?? DateTimeOffset.UtcNow;
        CompletedBy = completedBy;
        Notes       = notes;
        UpdatedBy   = completedBy;
        UpdatedAt   = CompletedAt.Value;
    }

    /// <summary>Mark the task not-applicable for this occurrence (e.g., asset removed).</summary>
    public void MarkNotApplicable(Guid markedBy, string? notes = null, DateTimeOffset? markedAt = null)
    {
        Status    = MaintenanceTaskStatus.NotApplicable;
        Notes     = notes;
        UpdatedBy = markedBy;
        UpdatedAt = markedAt ?? DateTimeOffset.UtcNow;
    }

    /// <summary>Mark the task failed; follow-up required.</summary>
    public void Fail(Guid markedBy, string? notes = null, DateTimeOffset? markedAt = null)
    {
        Status    = MaintenanceTaskStatus.Failed;
        Notes     = notes;
        UpdatedBy = markedBy;
        UpdatedAt = markedAt ?? DateTimeOffset.UtcNow;
    }
}
