<#
.SYNOPSIS
    Build an unsigned Sunfish MSI using WiX Toolset v4.

.DESCRIPTION
    Wave 4.5 scaffolding. Produces installers/windows/output/Sunfish.msi.
    See installers/windows/README.md for context, signing guidance, and
    known gaps.

.PARAMETER Version
    Version stamped into the MSI. Default: 0.0.0-dev.

.PARAMETER Configuration
    dotnet publish configuration. Default: Release.

.PARAMETER Runtime
    RID to publish for. Default: win-x64.

.EXAMPLE
    pwsh -File installers/windows/build-msi.ps1 -Version 0.1.0-preview
#>

[CmdletBinding()]
param(
    [string]$Version        = '0.0.0-dev',
    [string]$Configuration  = 'Release',
    [string]$Runtime        = 'win-x64'
)

$ErrorActionPreference = 'Stop'

function Write-Step($message) {
    Write-Host "[msi] $message" -ForegroundColor Cyan
}

$repoRoot    = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path
$appProject  = Join-Path $repoRoot 'apps/local-node-host/Sunfish.LocalNodeHost.csproj'
$publishDir  = Join-Path $PSScriptRoot 'publish'
$wixDir      = Join-Path $PSScriptRoot 'wix'
$outputDir   = Join-Path $PSScriptRoot 'output'

# 1. Publish the Worker Service as a self-contained, trimmed binary.
Write-Step "Publishing $appProject ($Configuration, $Runtime)…"
if (Test-Path $publishDir) { Remove-Item -Recurse -Force $publishDir }
dotnet publish $appProject `
    --configuration $Configuration `
    --runtime $Runtime `
    --self-contained true `
    --output $publishDir `
    /p:PublishSingleFile=false `
    /p:Version=$Version
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed ($LASTEXITCODE)." }

# 2. Generate WiX authoring if missing. Kept in-script so contributors do not
#    have to edit two files when paths or component layouts change.
if (-not (Test-Path $wixDir)) { New-Item -ItemType Directory -Path $wixDir | Out-Null }

$wxs = Join-Path $wixDir 'SunfishLocalNodeHost.wxs'
$wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sunfish Local-Node Host — WiX v4 authoring.
  Auto-generated by build-msi.ps1; edits here will be overwritten on next run.
-->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="Sunfish Local-Node Host"
           Manufacturer="Sunfish"
           Version="$Version"
           UpgradeCode="c9b6f1de-3c1a-4c11-9cba-000000000001"
           InstallerVersion="500"
           Scope="perMachine">

    <MajorUpgrade DowngradeErrorMessage="A newer version of Sunfish is already installed." />

    <Feature Id="ProductFeature" Title="Sunfish" Level="1">
      <ComponentGroupRef Id="ProductComponents" />
      <ComponentRef Id="ServiceComponent" />
    </Feature>

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="SUNFISHROOT" Name="Sunfish">
        <Directory Id="INSTALLFOLDER" Name="LocalNodeHost" />
      </Directory>
    </StandardDirectory>

    <!--
      ServiceInstall registers the SunfishLocalNode Windows Service. It runs
      under LocalSystem with Automatic start. BYOD path-separation (paper
      §16.3) means the service does NOT write to %LOCALAPPDATA%\Sunfish\
      UserPreferences — only to %LOCALAPPDATA%\Sunfish\TeamData.
    -->
    <Component Id="ServiceComponent" Directory="INSTALLFOLDER" Guid="c9b6f1de-3c1a-4c11-9cba-000000000002">
      <File Id="HostExe" Source="`$(var.PublishDir)\Sunfish.LocalNodeHost.exe" KeyPath="yes" />
      <ServiceInstall Id="SunfishLocalNodeService"
                      Name="SunfishLocalNode"
                      DisplayName="Sunfish Local Node"
                      Type="ownProcess"
                      Start="auto"
                      ErrorControl="normal"
                      Description="Headless Sunfish local-node kernel host."
                      Account="LocalSystem"
                      Vital="yes" />
      <ServiceControl Id="StartService"
                      Name="SunfishLocalNode"
                      Start="install"
                      Stop="both"
                      Remove="uninstall"
                      Wait="yes" />
    </Component>
  </Package>

  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
      <!-- Other published assets are harvested by heat.exe in a future pass. -->
    </ComponentGroup>
  </Fragment>
</Wix>
"@
Set-Content -LiteralPath $wxs -Value $wxsContent -Encoding UTF8

# 3. Build the MSI via the `wix` global tool.
if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir | Out-Null }
$msiPath = Join-Path $outputDir 'Sunfish.msi'

Write-Step "Invoking wix build…"
& wix build `
    -d "PublishDir=$publishDir" `
    -out $msiPath `
    $wxs
if ($LASTEXITCODE -ne 0) { throw "wix build failed ($LASTEXITCODE)." }

Write-Step "MSI built: $msiPath"

# 4. Signing stub. Uncomment and adapt in a production release pass.
# Invoke-SignTool -File $msiPath -Cert '<thumbprint>' `
#                 -TimestampUrl 'http://timestamp.digicert.com'
Write-Step "Signing skipped (Wave 4.5 scaffolding). See README for production guidance."
